name: Reset gh-pages branch

on:
  schedule:
    # Every tuesday at 11.30am UTC (7.30am ET)
    - cron: "30 11 * * 2"
  workflow_dispatch:

jobs:
  gh-pages-reset:
    name: Reset gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reset gh-pages branch
        run: |
          ./gh-pages-reset.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
